/**
 * Round-trip preservation tests.
 *
 * Each test verifies that a specific markdown construct passes through the
 * parse → stringify pipeline without any transformation.  This file acts as a
 * living specification of what the pipeline MUST NOT corrupt.
 *
 * Covered constructs:
 *  - Obsidian wikilinks  [[Page]] / ![[image.png]]
 *  - Angle-bracket expressions containing asterisks  <* … *>
 *  - Templater JS blocks  <%* … %>
 *  - Nested unordered lists (all levels use the canonical `*` bullet)
 *  - YAML front-matter
 *  - Emphasis that uses `*` as a delimiter (*italic*)
 *  - Escaped asterisks that must remain escaped  \*literal\*
 */
import { describe, it, expect } from "vitest";
import { runInitPass } from "../src/engine/runner.js";
import fs from "node:fs/promises";
import { normalizeFileContent } from "../src/engine/runner.js";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createParseProcessor } from "../src/markdown/parse.js";
import { EMPTY_CONFIG } from "../src/markdown/defaultConfig.js";
import type { Paragraph } from "mdast";
import { buildJobId } from "../src/engine/actions/requestTranscription.js";

// Repro: bullet list with nested numbered list
// (was de-indented and got an extra blank line in some remark-stringify versions)
const NESTED_ORDERED_IN_UNORDERED =
  "* bulleted list\n  1. Nested numbered list\n  2. Next item\n";

// ---------------------------------------------------------------------------
// Wikilinks
// ---------------------------------------------------------------------------

describe("round-trip: wikilinks", () => {
  it("preserves page wikilink [[Page Name]]", () => {
    const src = "[[Some Link]]\n";
    expect(normalizeFileContent(src)).toBe(src);
  });

  it("preserves inline image wikilink ![[file.png]]", () => {
    const src = "![[Projects/2022-05-07_09.18.50.png]]\n";
    expect(normalizeFileContent(src)).toBe(src);
  });

  it("preserves wikilink with underscores in filename", () => {
    const src = "![[archive/meeting_notes_2024.png]]\n";
    expect(normalizeFileContent(src)).toBe(src);
  });

  it("preserves wikilink inside a task list item", () => {
    const src = "* [ ] Review ![[diagram_v2.png]]\n";
    expect(normalizeFileContent(src)).toBe(src);
  });

  it("preserves multiple wikilinks on the same line", () => {
    const src = "See [[Note 1]] and also [[Note 2]] for details.\n";
    expect(normalizeFileContent(src)).toBe(src);
  });

  it("preserves nested list with wikilinks at each level", () => {
    const src =
      "* Top level [[link]]\n  * Nested [[link2]]\n    * Deep [[link3]]\n";
    expect(normalizeFileContent(src)).toBe(src);
  });

  it("preserves wikilink with path separator", () => {
    const src = "See [[Archive/Old Project]] for history.\n";
    expect(normalizeFileContent(src)).toBe(src);
  });
});

// ---------------------------------------------------------------------------
// Asterisks in non-emphasis contexts
// ---------------------------------------------------------------------------

describe("round-trip: asterisks in non-emphasis contexts", () => {
  it("preserves <* … *> angle-bracket tag syntax", () => {
    // Both * are inert: the first is not left-flanking (followed by space),
    // the second is not right-flanking (preceded by space).
    const src = "<* something *>\n";
    expect(normalizeFileContent(src)).toBe(src);
  });

  it("preserves Templater <%* … %> block syntax", () => {
    // The * in <%* is not left-flanking (followed by space).
    const src = "<%* const title = tp.file.title; %>\n";
    expect(normalizeFileContent(src)).toBe(src);
  });

  it("preserves Templater <%* in a task", () => {
    const src = "* [ ] Generated by <%* tR += tp.file.title %>\n";
    expect(normalizeFileContent(src)).toBe(src);
  });

  it("does NOT strip escaping from * that would form emphasis", async () => {
    // \*foo\* in the source is literal text: the pipeline must keep it escaped
    // so that re-parsing still produces a text node, not <em>foo</em>.
    const src = "\\*foo\\* bar\n";
    const out = normalizeFileContent(src);

    // make a temporary state directory in the operating system's temp area, which the parse processor may need for plugin context
    const __dirname = dirname(fileURLToPath(import.meta.url));
    const stateDir = join(__dirname, "tmp", "roundtrip-test-state");
    await fs.mkdir(stateDir, { recursive: true });

    const vaultPath = "";

    // The output representation may differ slightly but the rendered semantics
    // must be identical: the * characters must not form an emphasis node.
    const tree = createParseProcessor(vaultPath, EMPTY_CONFIG, {
      todayDate: new Date(),
      vaultPath,
      addTasks: {},
      alertTasks: [],
      async queueJob() {},
      jobIdFactory: buildJobId,
    }).parse(out);
    const para = tree.children[0] as Paragraph;
    // All children must be text — no emphasis node.
    for (const child of para.children) {
      expect(child.type).toBe("text");
    }
  });

  it("preserves actual *emphasis* unchanged", () => {
    // *foo* should remain as *foo* (emphasis node round-trips cleanly).
    const src = "*foo* bar\n";
    expect(normalizeFileContent(src)).toBe(src);
  });
});

// ---------------------------------------------------------------------------
// Nested lists
// ---------------------------------------------------------------------------

describe("round-trip: nested lists", () => {
  it("preserves 2-space nested unordered list", () => {
    const src = "* Item 1\n  * Nested 1\n  * Nested 2\n* Item 2\n";
    expect(normalizeFileContent(src)).toBe(src);
  });

  it("preserves three-level nesting", () => {
    const src = "* Level 1\n  * Level 2\n    * Level 3\n";
    expect(normalizeFileContent(src)).toBe(src);
  });

  it("preserves nested task lists", () => {
    const src =
      "* [ ] Parent task\n" +
      "  * [ ] Child task\n" +
      "    * [ ] Grandchild\n" +
      "  * [ ] Another child\n" +
      "* [ ] Second parent\n";
    expect(normalizeFileContent(src)).toBe(src);
  });

  it("preserves ordered list nested inside unordered", () => {
    const src = "* Item\n  1. First\n  2. Second\n* Another item\n";
    expect(normalizeFileContent(src)).toBe(src);
  });

  it("preserves loose nested list (blank lines between items)", () => {
    const src = "* Item 1\n\n  * Nested 1\n\n  * Nested 2\n\n* Item 2\n";
    expect(normalizeFileContent(src)).toBe(src);
  });

  // Regression: remark-stringify with listItemIndent:'one' lost indentation
  // and inserted a blank line when a numbered list was nested inside a bullet.
  it("preserves nested numbered list in bullet — exact repro", () => {
    expect(normalizeFileContent(NESTED_ORDERED_IN_UNORDERED)).toBe(
      NESTED_ORDERED_IN_UNORDERED,
    );
  });

  it("is idempotent for nested numbered list inside bullet list", () => {
    const once = normalizeFileContent(NESTED_ORDERED_IN_UNORDERED);
    expect(normalizeFileContent(once)).toBe(once);
  });
});

// ---------------------------------------------------------------------------
// YAML front-matter
// ---------------------------------------------------------------------------

describe("round-trip: YAML front-matter", () => {
  it("preserves front-matter block via normalizeFileContent", async () => {
    // normalizeFileContent splits frontmatter from body before parse/stringify,
    // so the YAML block is never fed to remark and cannot be corrupted.
    const src =
      "---\ntitle: My Note\ntags:\n  - project\n---\n\n# Heading\n\nBody text.\n";
    expect(await normalizeFileContent(src)).toBe(src);
  });

  it("does not convert publish:false frontmatter into a Markdown heading", async () => {
    // Regression: the closing `---` of a frontmatter block was mis-parsed
    // by remark as a setext heading underline, turning `publish: false\n---`
    // into `## publish: false`.  normalizeFileContent must prevent this by
    // stripping frontmatter before passing the body to remark.
    const src = "---\npublish: false\n---\n";
    expect(await normalizeFileContent(src)).toBe(src);
  });

  it("normalizeFileContent preserves nested numbered list in bullet list", async () => {
    // Regression: bullet → ordered nesting must survive the full normalise
    // pipeline (parseFrontmatter → parseMarkdown → stringifyMarkdown) without
    // losing indentation or gaining a blank line between the two lists.
    expect(await normalizeFileContent(NESTED_ORDERED_IN_UNORDERED)).toBe(
      NESTED_ORDERED_IN_UNORDERED,
    );
  });
});

// ---------------------------------------------------------------------------
// UTF-16 → UTF-8 conversion
// ---------------------------------------------------------------------------

describe("round-trip: UTF-16 decoding", () => {
  it("decodes UTF-16 LE content to the same text as UTF-8", async () => {
    const __dir = dirname(fileURLToPath(import.meta.url));

    const TMP = join(__dir, "..", "tmp", "roundtrip-utf16-test");
    await fs.mkdir(TMP, { recursive: true });
    try {
      const text = "Speaker 1  (00:03)\n";
      const utf16Buf = Buffer.concat([
        Buffer.from([0xff, 0xfe]),
        Buffer.from(text, "utf16le"),
      ]);
      const filePath = join(TMP, "transcript.md");
      await fs.writeFile(filePath, utf16Buf);

      await runInitPass(TMP, false);

      const result = await fs.readFile(filePath, "utf-8");
      expect(result).toContain("Speaker 1  (00:03)");
      // No BOM in the output
      const resultBuf = await fs.readFile(filePath);
      expect(resultBuf[0]).not.toBe(0xff);
    } finally {
      await fs.rm(TMP, { recursive: true, force: true });
    }
  });
});
